version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/code-deploy/stop_server
      runas: ec2-user
      timeout: 300
  BeforeInstall:
    - location: scripts/code-deploy/install_dependencies
      runas: ec2-user
      timeout: 300
  AfterInstall:
    - location: scripts/code-deploy/after_install
      runas: ec2-user
      timeout: 600
  ApplicationStart:
    - location: scripts/code-deploy/start_server
      runas: ec2-user
      timeout: 300

